# Generated by Django 4.2.7 on 2023-12-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_channel',
            field=models.IntegerField(default=1),
        ),
    ]
