# Generated by Django 4.2.7 on 2023-12-12 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_task_assigned_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.kanban'),
        ),
    ]
