# Generated by Django 4.2.7 on 2023-12-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_alter_task_assigned_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('to_do', 'to_do'), ('in_progress', 'in_progress'), ('testing', 'testing'), ('done', 'done')], default='done', max_length=20),
            preserve_default=False,
        ),
    ]
